'use strict';

var React = require('react-native');

var {
  StyleSheet,
} = React;

module.exports = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  scrollable_container: {
    width: '100%',
    height: '75%',
  },
  INSOLAR_logo: {
    alignItems: 'flex-start',
    width: '80%',
    height: 100,
  },
  bg: {
    width: '100%',
    height: 550,
  },
  bg_img: {
    width: '100%',
    height: '100%',
  },
  bg_thirdblock: {
    backgroundColor: '#4682B4',
    width: '100%',
    padding: 15,
  },
  bg_innerblock: {
    margin: 10,
    backgroundColor: 'white',
  },
  bg_innerblock2: {
    backgroundColor:'white',
    margin: 5,
  },
  bg_fourthblock: {
    backgroundColor: '#DCDCDC',
    width: '100%',
    padding: 7,
  },
  article_block: {
    margin: 10,
    backgroundColor: '#F5FCFF',
  },
  slogan_1: {
    position: 'absolute',
    top: 70,
    alignSelf: 'center',
    fontSize: 40,
    textAlign: 'center',
    color: "#FFFFFF",
    fontWeight: 'bold',
  },
  slogan_2: {
    position: 'absolute',
    top: 130,
    alignSelf: 'center',
    fontSize: 40,
    textAlign: 'center',
    color: "#FFFFFF",
    fontWeight: 'bold',
  },
  slogan_3: {
    position: 'absolute',
    top: 350,
    alignSelf: 'center',
    fontSize: 18,
    textAlign: 'center',
    color: "#FFFFFF",
  },
  btn_container: {
    width: "60%",
    position: 'absolute',
    top: 420,
    alignSelf: 'center',
    backgroundColor: "#54B948",
    borderRadius: 5,
  },
  btn_container2: {
    width: "60%",
    position: 'absolute',
    top: 150,
    alignSelf: 'center',
    backgroundColor: "#54B948",
    borderRadius: 5,
  },
  btn_green: {
    width: "60%",
    alignSelf: 'center',
    backgroundColor: "#54B948",
    borderRadius: 5,
    marginTop: 15,
    marginBottom: 50,
  },
  nav_btn_container: {
    height: 30,
    paddingTop: 3,
    bottom: 0,
    flexDirection: 'row',
  },
  nav_text: {
    fontSize: 18,
    color: 'gray',
    textAlign: 'center',
  },
  sm_heading: {
    fontSize: 14,
    margin: 30,
    textAlign: 'center',
  },
  heading: {
    fontSize: 24,
    fontWeight: 'bold',
    margin: 30,
    textAlign: 'center',
  },
  heading2: {
    fontSize: 20,
    fontWeight: 'bold',
    marginTop: 30,
    marginBottom: 10,
    textAlign: 'center',
  },
  heading3: {
    fontSize: 20,
    fontWeight: 'bold',
    marginTop: 30,
    textAlign: 'center',
    color: 'skyblue',
  },
  heading4: {
    fontSize: 24,
    fontWeight: 'bold',
    margin: 15,
    textAlign: 'left',
  },
  heading5: {
    color: 'gray',
    fontSize: 20,
    fontWeight: 'bold',
    marginTop: 30,
    marginBottom: 10,
    textAlign: 'center',
  },
  heading6: {
    fontSize: 24,
    fontWeight: 'bold',
    margin: 15,
    textAlign: 'left',
    color: '#FF69B4',
  },
  separator: {
    width: '100%',
    height: 1,
    backgroundColor: 'lightgray',
  },
  separator2: {
    width: '10%',
    height: 3,
    backgroundColor: '#FF69B4',
    alignSelf: 'center',
  },
  separator3: {
    width: '90%',
    height: 3,
    backgroundColor: '#FF69B4',
    alignSelf: 'center',
  },
  icon: {
    width: '100%',
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
  },
  content: {
    fontSize:16,
    color: 'gray',
    marginBottom: 30,
    marginLeft: 10,
    marginRight: 10,
    textAlign: 'center',
  },
  content2: {
    fontSize: 16,
    textAlign: 'left',
    margin: 18,
  },
  content3: {
    fontSize:16,
    color: 'gray',
    marginBottom: 30,
    marginLeft: 10,
    marginTop: 20,
    marginRight: 10,
    textAlign: 'center',
  },
  content4: {
    fontSize:16,
    color: 'gray',
    marginBottom: 30,
    marginLeft: 10,
    marginTop: 5,
    marginRight: 10,
    textAlign: 'center',
  },
  content5: {
    fontSize:16,
    color: 'gray',
    marginBottom: 30,
    marginLeft: 10,
    marginTop: 20,
    marginRight: 10,
    textAlign: 'left',
  },
  side_img: {
    margin: 5,
    width: '100%',
    height: 300,
  },
  
});
